import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Wasims T-Shirt Hub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
      </Head>

      <main className={styles.main}>
        {/* Hero */}
        <div className={styles.hero_container}>
          <img className={styles.hero_image} src="hero.jpg" alt="" />
          <div className={styles.hero_text_container}>
            <h1>Shop for Trendy Custom Designed T-Shirts</h1>
            <Link href="/products">
              <button>SHOP</button>
            </Link>
            <Link href="/contact">
              <button>CUSTOM ORDER</button>
            </Link>
          </div>
        </div>
        {/* Categories */}
        <div className={styles.categories}>
          <div className={styles.category_item}>
            <div className={styles.image_container}>
              <img src="mens.jpg" alt="" />
            </div>

            <Link href="/">
              <button>MENS</button>
            </Link>
          </div>
          <div className={styles.category_item}>
            <div className={styles.image_container}>
              <img src="womens.jpg" alt="" />
            </div>

            <Link href="/">
              <button>WOMENS</button>
            </Link>
          </div>
          <div className={styles.category_item}>
            <div className={styles.image_container}>
              <img src="kids.jpg" alt="" />
            </div>

            <Link href="/">
              <button>KIDS</button>
            </Link>
          </div>
          <div className={styles.category_item}>
            <div className={styles.image_container}>
              <img src="unisex.jpg" alt="" />
            </div>

            <Link href="/">
              <button>UNISEX</button>
            </Link>
          </div>
        </div>
        {/* Top Selling Items */}
        <div className={styles.product_grid}>
          <div className={styles.product_item}>
            <div className={styles.product_image_container}>
              <img className={styles.product_image} src="product1.jpg" alt="" />
              <p className={styles.tag}>NEW</p>
              <button className={styles.addtocart}>ADD TO CART</button>
            </div>
            <h3 className={styles.product_name}>Product Name</h3>
            <p className={styles.product_price}>1620 LKR</p>
          </div>

          <div className={styles.product_item}>
            <div className={styles.product_image_container}>
              <img className={styles.product_image} src="product2.jpg" alt="" />
              <p className={styles.tag}>NEW</p>
              <button className={styles.addtocart}>ADD TO CART</button>
            </div>
            <h3 className={styles.product_name}>Product Name</h3>
            <p className={styles.product_price}>1620 LKR</p>
          </div>

          <div className={styles.product_item}>
            <div className={styles.product_image_container}>
              <img className={styles.product_image} src="product3.jpg" alt="" />
              <p className={styles.tag}>NEW</p>
              <button className={styles.addtocart}>ADD TO CART</button>
            </div>
            <h3 className={styles.product_name}>Product Name</h3>
            <p className={styles.product_price}>1620 LKR</p>
          </div>

          <div className={styles.product_item}>
            <div className={styles.product_image_container}>
              <img className={styles.product_image} src="product4.jpg" alt="" />
              <p className={styles.tag}>NEW</p>
              <button className={styles.addtocart}>ADD TO CART</button>
            </div>
            <h3 className={styles.product_name}>Product Name</h3>
            <p className={styles.product_price}>1620 LKR</p>
          </div>
        </div>
        {/* Promotion Banner */}
        <div className={styles.promotion_banner}>
          <div className={styles.promition_image_container}>
            <img
              className={styles.promition_image_container}
              src="unisex.jpg"
              alt=""
            />
          </div>
          <div className={styles.promition_right}>
            <h2 className={styles.promotion_text}>
              black friday sales upto
              <span className={styles.promo_highlight}> 30% off</span>
            </h2>
            <Link className={styles.promotion_link} href="/">
              <button>grab the deal</button>
            </Link>
          </div>
        </div>
        {/* Why Us */}
        <div className={styles.why}>
          <div className={styles.why_container}>
            <div className={styles.why_logo}>
              <img width={200} src="quality.svg" alt="" />
            </div>
            <div className={styles.why_details}>
              <h3 className={styles.why_title}>Quality Products</h3>
              <p className={styles.why_text}>
                Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                Doloremque blanditiis corporis voluptas vero illum. Eius quas
                voluptatem reiciendis maxime expedita?
              </p>
            </div>
          </div>

          <div className={styles.why_container}>
            <div className={styles.why_logo}>
              <img width={200} src="fair.svg" alt="" />
            </div>
            <div className={styles.why_details}>
              <h3 className={styles.why_title}>Fair Price</h3>
              <p className={styles.why_text}>
                Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                Doloremque blanditiis corporis voluptas vero illum. Eius quas
                voluptatem reiciendis maxime expedita?
              </p>
            </div>
          </div>

          <div className={styles.why_container}>
            <div className={styles.why_logo}>
              <img width={200} src="fast.svg" alt="" />
            </div>

            <div className={styles.why_details}>
              <h3 className={styles.why_title}>Fast Delivery</h3>
              <p className={styles.why_text}>
                Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                Doloremque blanditiis corporis voluptas vero illum. Eius quas
                voluptatem reiciendis maxime expedita?
              </p>
            </div>
          </div>
        </div>

        {/* FAQs */}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
