import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Wasims T-Shirt Hub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
      </Head>

      <main className={styles.main}>
        {/* Hero */}
        <div className={styles.hero_container}>
          <img className={styles.hero_image} src="hero.jpg" alt="" />
          <div className={styles.hero_text_container}>
            <h1>Shop for Trendy Custom Designed T-Shirts</h1>
            <Link href="/products">
              <button>SHOP</button>
            </Link>
            <Link href="/contact">
              <button>CUSTOM ORDER</button>
            </Link>
          </div>
        </div>
        {/* Categories */}
        <div className={styles.categories}>
          <div className={styles.category_item}>
            <div className={styles.image_container}>
              <img src="mens.jpg" alt="" />
            </div>

            <Link href="/">
              <button>MENS</button>
            </Link>
          </div>
          <div className={styles.category_item}>
            <div className={styles.image_container}>
              <img src="womens.jpg" alt="" />
            </div>

            <Link href="/">
              <button>WOMENS</button>
            </Link>
          </div>
          <div className={styles.category_item}>
            <div className={styles.image_container}>
              <img src="kids.jpg" alt="" />
            </div>

            <Link href="/">
              <button>KIDS</button>
            </Link>
          </div>
          <div className={styles.category_item}>
            <div className={styles.image_container}>
              <img src="unisex.jpg" alt="" />
            </div>

            <Link href="/">
              <button>UNISEX</button>
            </Link>
          </div>
        </div>
        {/* Top Selling Items */}
        {/* Promotion Banner */}
        {/* Why Us */}
        {/* FAQs */}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
